project:
  type: website
  output-dir: .

website:
  title: "Hayk Mardanyan"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true